const emitter = require('../eventBus')

emitter.on( 'GOOD_MORNING', require('./good-morning') )
emitter.on( 'HELLO', require('./hello') )
emitter.on( 'HELP', require('./help') )
emitter.on( 'MY_SELF', require('./my-self') )
emitter.on( 'SCORE', require('./score') )
emitter.on( 'ISSUES', require('./issues') )
emitter.on( 'LOGIN', require('./login') )
emitter.on( 'GOAL', require('./goal') )
emitter.on( 'TOP10', require('./top10') )